version: '3.8'

services:
  build_ws:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/ros2_ws/src/scout_nav2
      - ros2_ws_vol:/ros2_ws
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
              cd /ros2_ws &&
              rosdep install --from-paths src --ignore-src -r -y &&
              colcon build --cmake-clean-cache"

  simulation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/ros2_ws/src/scout_nav2
      - ros2_ws_vol:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    tty: true
    depends_on:
      build_ws:
        condition: service_completed_successfully
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
              source /ros2_ws/install/setup.bash &&
              ros2 launch robot_description simulate_control_gazebo.launch.py lidar_type:=2d rviz:=false"

  navigation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/ros2_ws/src/scout_nav2
      - ros2_ws_vol:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    tty: true
    depends_on:
      simulation:
        condition: service_started
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
              source /ros2_ws/install/setup.bash &&
              ros2 launch rm_navigation nav2.launch.py simulation:=true slam:=true localization:=amcl"

  waypoint_publisher:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/ros2_ws/src/scout_nav2
      - ros2_ws_vol:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    tty: true
    depends_on:
      navigation:
        condition: service_started
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
              source /ros2_ws/install/setup.bash &&
              ros2 run waypoint_navigation_pkg waypoint_navigation_node"

volumes:
  ros2_ws_vol: